Repository meongmory/meongmory_iOS, pull requests merged in 2023-08, with the labels that each got.

#6 Feat/2 map UI
  Podfile
  meongmory_iOS.xcodeproj/project.pbxproj
  meongmory_iOS.xcodeproj/xcuserdata/yoosang.xcuserdatad/xcschemes/xcschememanagement.plist
  meongmory_iOS/Business/Interactor/Map/LocationManager.swift
  meongmory_iOS/Presentation/View/Map/MapView.swift
  meongmory_iOS/meongmory_iOSApp.swift
Labels: 🍽 feature

#9 [Feat] 네이버 지도 sdk 설치 (pod)
  Podfile
  meongmory_iOS.xcodeproj/project.pbxproj
  meongmory_iOS.xcodeproj/xcuserdata/yoosang.xcuserdatad/xcschemes/xcschememanagement.plist
  meongmory_iOS/ContentView.swift
  meongmory_iOS/Presentation/View/Map/MapView.swift
Labels: 🔒 config

#12 [Feature] 마이페이지 UI 구현
  meongmory_iOS.xcodeproj/project.pbxproj
  meongmory_iOS/Assets.xcassets/mypage/arrow-gray.imageset/arrow-gray@1x.png
  meongmory_iOS/Assets.xcassets/mypage/arrow-gray.imageset/arrow-gray@2x.png
  meongmory_iOS/Assets.xcassets/mypage/arrow-gray.imageset/arrow-gray@3x.png
  meongmory_iOS/Assets.xcassets/mypage/arrowtriangle-down-gray.imageset/Contents.json
  meongmory_iOS/Assets.xcassets/mypage/arrowtriangle-down-gray.imageset/arrowtriangle.down.gray@1x.png
  meongmory_iOS/Assets.xcassets/mypage/arrowtriangle-down-gray.imageset/arrowtriangle.down.gray@2x.png
  meongmory_iOS/Assets.xcassets/mypage/arrowtriangle-down-gray.imageset/arrowtriangle.down.gray@3x.png
  meongmory_iOS/Assets.xcassets/mypage/chevron-gray.imageset/Contents.json
  meongmory_iOS/Assets.xcassets/mypage/chevron-gray.imageset/gray_chevron@1x.png
  meongmory_iOS/Assets.xcassets/mypage/chevron-gray.imageset/gray_chevron@2x.png
  meongmory_iOS/Assets.xcassets/mypage/chevron-gray.imageset/gray_chevron@3x.png
  meongmory_iOS/Assets.xcassets/mypage/report.imageset/Contents.json
  meongmory_iOS/Assets.xcassets/mypage/report.imageset/send@1x.png
  meongmory_iOS/Assets.xcassets/mypage/report.imageset/send@2x.png
  meongmory_iOS/Assets.xcassets/mypage/report.imageset/send@3x.png
  meongmory_iOS/ContentView.swift
  meongmory_iOS/Presentation/View/MyPage/Components/MypageMenuListView.swift
  meongmory_iOS/Presentation/View/MyPage/Components/MypageMenuRow.swift
  meongmory_iOS/Presentation/View/MyPage/Components/UserProfilView.swift
  meongmory_iOS/Presentation/View/MyPage/EMenuDetail.swift
  meongmory_iOS/Presentation/View/MyPage/EditProfileView.swift
  meongmory_iOS/Presentation/View/MyPage/MenuDetailView/NoticeView.swift
  meongmory_iOS/Presentation/View/MyPage/MenuDetailView/ProVersionView.swift
  meongmory_iOS/Presentation/View/MyPage/MenuDetailView/ReportView.swift
  meongmory_iOS/Presentation/View/MyPage/MenuDetailView/TermWebView.swift
  meongmory_iOS/Presentation/View/MyPage/MyPageView.swift
  meongmory_iOS/Presentation/View/MyPage/ProVersionView.swift
  meongmory_iOS/Presentation/View/MyPage/SetNotificationView.swift
  meongmory_iOS/Presentation/View/MyPage/WebView.swift
Labels: 🍽 feature

#13 [Config] 웹뷰 사용을 위한 info.plist 속성 추가
  meongmory-iOS-Info.plist
Labels: 🔒 config

#16 [Feature] 회원가입/로그인 UI 구현
  meongmory_iOS.xcodeproj/project.pbxproj
  meongmory_iOS/Assets.xcassets/main_icon.imageset/Contents.json
  meongmory_iOS/Assets.xcassets/main_icon.imageset/main_icon@1x.png
  meongmory_iOS/Assets.xcassets/main_icon.imageset/main_icon@2x.png
  meongmory_iOS/Assets.xcassets/main_icon.imageset/main_icon@3x.png
  meongmory_iOS/Assets.xcassets/main_text_icon.imageset/Contents.json
  meongmory_iOS/Assets.xcassets/main_text_icon.imageset/main_text_icon@1x.png
  meongmory_iOS/Assets.xcassets/main_text_icon.imageset/main_text_icon@2x.png
  meongmory_iOS/Assets.xcassets/main_text_icon.imageset/main_text_icon@3x.png
  meongmory_iOS/Assets.xcassets/onboarding_image/Contents.json
  meongmory_iOS/Assets.xcassets/onboarding_image/onboard1.imageset/Contents.json
  meongmory_iOS/Assets.xcassets/onboarding_image/onboard1.imageset/onboard1@1x.png
  meongmory_iOS/Assets.xcassets/onboarding_image/onboard1.imageset/onboard1@2x.png
  meongmory_iOS/Assets.xcassets/onboarding_image/onboard1.imageset/onboard1@3x.png
  meongmory_iOS/Assets.xcassets/onboarding_image/onboard2.imageset/Contents.json
  meongmory_iOS/Assets.xcassets/onboarding_image/onboard2.imageset/onboard2@1x.png
  meongmory_iOS/Assets.xcassets/onboarding_image/onboard2.imageset/onboard2@2x.png
  meongmory_iOS/Assets.xcassets/onboarding_image/onboard2.imageset/onboard2@3x.png
  meongmory_iOS/Assets.xcassets/onboarding_image/onboard3.imageset/Contents.json
  meongmory_iOS/Assets.xcassets/onboarding_image/onboard3.imageset/onboard3@1x.png
  meongmory_iOS/Assets.xcassets/onboarding_image/onboard3.imageset/onboard3@2x.png
  meongmory_iOS/Assets.xcassets/onboarding_image/onboard3.imageset/onboard3@3x.png
  meongmory_iOS/Presentation/View/Auth/AgreeToTermsView.swift
  meongmory_iOS/Presentation/View/Auth/LoginView.swift
  meongmory_iOS/Presentation/View/Auth/OnBoardingView.swift
  meongmory_iOS/Presentation/View/Auth/SetNicknameView.swift
  meongmory_iOS/Presentation/View/Auth/ValidatePhoneNumView.swift
Labels: 🍽 feature

#17 [Fix] .prbxproj 파일 내 중괄호 누락 처리
  meongmory_iOS.xcodeproj/project.pbxproj
Labels: 🔨fix

#18 [Feat, Fix] 이용약관/개인정보처리방침 URL 추가, iPages SPM 누락 처리
  meongmory_iOS.xcodeproj/project.pbxproj
  meongmory_iOS/Presentation/View/MyPage/MenuDetailView/TermWebView.swift
Labels: 🍽 feature, 🔨fix

#20 [Fix, Feature] 마이페이지 내 아이콘 변경, 공지사항 목록 화면 UI 구현
  meongmory_iOS.xcodeproj/project.pbxproj
  meongmory_iOS/Assets.xcassets/mypage/log-out.imageset/log-out@1x.png
  meongmory_iOS/Assets.xcassets/mypage/log-out.imageset/log-out@2x.png
  meongmory_iOS/Assets.xcassets/mypage/log-out.imageset/log-out@3x.png
  meongmory_iOS/Assets.xcassets/mypage/notice.imageset/notice@1x.png
  meongmory_iOS/Assets.xcassets/mypage/notice.imageset/notice@2x.png
  meongmory_iOS/Assets.xcassets/mypage/notice.imageset/notice@3x.png
  meongmory_iOS/Assets.xcassets/mypage/privacy-term.imageset/privacy-term@1x.png
  meongmory_iOS/Assets.xcassets/mypage/privacy-term.imageset/privacy-term@2x.png
  meongmory_iOS/Assets.xcassets/mypage/privacy-term.imageset/privacy-term@3x.png
  meongmory_iOS/Assets.xcassets/mypage/pro-version.imageset/Contents.json
  meongmory_iOS/Assets.xcassets/mypage/pro-version.imageset/dollar-sign@1x.png
  meongmory_iOS/Assets.xcassets/mypage/pro-version.imageset/dollar-sign@2x.png
  meongmory_iOS/Assets.xcassets/mypage/pro-version.imageset/dollar-sign@3x.png
  meongmory_iOS/Assets.xcassets/mypage/pro-version.imageset/pro-version.png
  meongmory_iOS/Assets.xcassets/mypage/pro-version.imageset/pro-version@2x.png
  meongmory_iOS/Assets.xcassets/mypage/pro-version.imageset/pro-version@3x.png
  meongmory_iOS/Assets.xcassets/mypage/report.imageset/Contents.json
  meongmory_iOS/Assets.xcassets/mypage/report.imageset/report@1x.png
  meongmory_iOS/Assets.xcassets/mypage/report.imageset/report@2x.png
  meongmory_iOS/Assets.xcassets/mypage/report.imageset/report@3x.png
  meongmory_iOS/Assets.xcassets/mypage/report.imageset/send@1x.png
  meongmory_iOS/Assets.xcassets/mypage/report.imageset/send@2x.png
  meongmory_iOS/Assets.xcassets/mypage/report.imageset/send@3x.png
  meongmory_iOS/Assets.xcassets/mypage/sign-out.imageset/sign-out@1x.png
  meongmory_iOS/Assets.xcassets/mypage/sign-out.imageset/sign-out@2x.png
  meongmory_iOS/Assets.xcassets/mypage/sign-out.imageset/sign-out@3x.png
  meongmory_iOS/Assets.xcassets/mypage/term.imageset/term@1x.png
  meongmory_iOS/Assets.xcassets/mypage/term.imageset/term@2x.png
  meongmory_iOS/Assets.xcassets/mypage/term.imageset/term@3x.png
  meongmory_iOS/Presentation/View/MyPage/Components/NoticeRow.swift
  meongmory_iOS/Presentation/View/MyPage/Components/UserProfilView.swift
  meongmory_iOS/Presentation/View/MyPage/MenuDetailView/NoticeDetailView.swift
  meongmory_iOS/Presentation/View/MyPage/MenuDetailView/NoticeView.swift
Labels: 🍽 feature, 🔨fix

#21 [Feature] 홈 UI 구현
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .gitignore
  Podfile.lock
  README.md
  meongmory_iOS.xcodeproj/project.pbxproj
  meongmory_iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  meongmory_iOS/Assets.xcassets/home/Contents.json
  meongmory_iOS/Assets.xcassets/home/bell.imageset/Contents.json
  meongmory_iOS/Assets.xcassets/home/bell.imageset/bell 1.png
  meongmory_iOS/Assets.xcassets/home/bell.imageset/bell 2.png
  meongmory_iOS/Assets.xcassets/home/bell.imageset/bell.png
  meongmory_iOS/Assets.xcassets/home/cafe.imageset/Contents.json
  meongmory_iOS/Assets.xcassets/home/cafe.imageset/cafe.png
  meongmory_iOS/Assets.xcassets/home/cute_puppy.imageset/Contents.json
  meongmory_iOS/Assets.xcassets/home/cute_puppy.imageset/cute_puppy.png
  meongmory_iOS/Assets.xcassets/home/market.imageset/Contents.json
  meongmory_iOS/Assets.xcassets/home/market.imageset/market.png
  meongmory_iOS/Assets.xcassets/home/pet_example.imageset/Contents.json
  meongmory_iOS/Assets.xcassets/home/pet_example.imageset/pet_example.png
  meongmory_iOS/Assets.xcassets/home/pet_example.imageset/pet_example2.png
  meongmory_iOS/Assets.xcassets/home/pet_example.imageset/pet_example3.png
  meongmory_iOS/Assets.xcassets/home/salon.imageset/Contents.json
  meongmory_iOS/Assets.xcassets/home/salon.imageset/salon.png
  meongmory_iOS/ContentView.swift
  meongmory_iOS/Presentation/View/Home/BusinessView.swift
  meongmory_iOS/Presentation/View/Home/FamilyLazyHGridCell.swift
  meongmory_iOS/Presentation/View/Home/FamilyListView.swift
  meongmory_iOS/Presentation/View/Home/HomeView.swift
  meongmory_iOS/Presentation/View/Home/RecommendedView.swift
Labels: 🔒 config, 🍽 feature

#22 [Feature] 회원가입 중 약관 웹뷰 연결
  meongmory_iOS/Presentation/View/Auth/AgreeToTermsView.swift
Labels: 🍽 feature

#25 #feat: 다이어리 추가 및 반려동물 추가 ui 구현 (재업로드)
  meongmory_iOS.xcodeproj/project.pbxproj
  meongmory_iOS.xcworkspace/xcuserdata/yoosang.xcuserdatad/UserInterfaceState.xcuserstate
  meongmory_iOS/Extension/CGFloat+.swift
  meongmory_iOS/Presentation/View/Diary/AddDiaryView.swift
  meongmory_iOS/Presentation/View/Diary/AddPetView.swift
  meongmory_iOS/Presentation/View/Diary/CompleteAddPetView.swift
  meongmory_iOS/Presentation/View/Diary/InviteCodeView.swift
  meongmory_iOS/Presentation/View/Diary/PetKindListRow.swift
  meongmory_iOS/Presentation/View/Diary/PetKindView.swift
  meongmory_iOS/Presentation/View/Diary/SelectAddDiaryView.swift
Labels: 🍽 feature
